w5d1_capybara_demo/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :subs
  resources :posts, except: [:index]
  resource :session, except: [:index, :update, :edit, :show]
end

w5d1_capybara_demo/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :sub_id, :author_id, presence: true

  belongs_to :sub

  belongs_to :author,
  foreign_key: :author_id,
  class_name: :User
end

w5d1_capybara_demo/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  mod_id      :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :mod_id, presence: true

  belongs_to :creator,
  foreign_key: :mod_id,
  class_name: :User

  has_many :posts

end

w5d1_capybara_demo/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token
  attr_reader :password

  has_many :posts,
  foreign_key: :author_id

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(10)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    digest = BCrypt::Password.new(self.password_digest)
    digest.is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    # session[:session_token] = nil
  end

  def password=(password)
    @password = password
    self.password_digest = generate_digest(password)
  end

  def generate_digest(password)
    BCrypt::Password.create(password)
  end
end

w5d1_capybara_demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :is_moderator?

  def require_current_user
    redirect_to new_session_url unless current_user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in(user)
    session[:session_token] = user.session_token
  end

  def is_moderator?
    sub = Sub.find_by_id(params[:id])
    current_user.id == sub.mod_id
  end

  def is_author?
    post = Post.find_by_id(params[:id])
    current_user.id == post.author_id
  end

  def log_out
    current_user.reset_session_token
    current_user.save
  end
end

w5d1_capybara_demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find_by_id(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
    redirect_to posts_url unless is_author?
  end

  def update
    @post = Post.find_by_id(params[:id])
    redirect_to posts_url unless is_author?
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :url, :author_id, :sub_id)
  end
end

w5d1_capybara_demo/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(session_params[:username], session_params[:password])
    if @user
      log_in(@user)
      redirect_to subs_url
    else
      render :new
    end
  end

  def destroy
    @user = User.find_by(session_token: session[:session_token])
    log_out if @user
    redirect_to new_session_url
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

w5d1_capybara_demo/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_current_user

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by_id(params[:id])
    redirect_to subs_url unless @sub
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def edit
    @sub = Sub.find_by_id(params[:id])
    redirect_to subs_url unless is_moderator?
  end

  def update
    @sub = Sub.find_by_id(params[:id])
    redirect_to subs_url unless is_moderator?
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description, :mod_id)
  end
end

w5d1_capybara_demo/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to subs_url
    else
      render :new
    end
  end

  # def edit
  # end
  #
  # def update
  # end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

w5d1_capybara_demo/app/helpers/application_helper.rb
module ApplicationHelper
end

w5d1_capybara_demo/app/helpers/posts_helper.rb
module PostsHelper
end

w5d1_capybara_demo/app/helpers/sessions_helper.rb
module SessionsHelper
end

w5d1_capybara_demo/app/helpers/subs_helper.rb
module SubsHelper
end

w5d1_capybara_demo/app/helpers/users_helper.rb
module UsersHelper
end

w5d1_capybara_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditOnRails</title>

  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <div class="nav-wrapper light-blue accent-3">
      <a href="/subs" class="brand-logo">RedditClone</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="<%= subs_url %>">Subs</a></li>
        <li><a href="badges.html">About</a></li>
        <li>
          <% if current_user %>
            <%= current_user.username %>
            <%= link_to 'Log Out', session_url, method: :delete %>
          <% else %>
            <%= link_to 'Log In', new_session_url, method: :get %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>

      <div class="container"
        <%= yield %>
      </div>
</body>
</html>

w5d1_capybara_demo/app/views/posts/_form.html.erb
<h2><%= action.capitalize %> Post</h2>

<% http = action == 'new' ? :post : :patch %>
<% url = action == 'new' ? posts_url : post_url(post) %>
<% sub_id = action == 'new' ? params[:sub_id] : post.sub_id %>
<form action="<%= url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= http %>">

  <input type="hidden" name="post[sub_id]" value="<%= sub_id %>">
  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">

  <label for="title">Title: </label>
  <input id='title' type="text" name="post[title]" value="<%= post.title %>">
  <br>
  <label for="url">URL: </label>
  <input id='url' type="text" name="post[url]" value="<%= post.url %>">
  <br>
  <label for="content">Content: </label>
  <textarea id='content' name="post[content]" rows="8" cols="80"><%= post.content %></textarea>

  <input type="submit" value="<%= action.capitalize %> Post">
</form>

w5d1_capybara_demo/app/views/posts/edit.html.erb
<%= render 'form', post: @post, action: 'edit' %>

w5d1_capybara_demo/app/views/posts/new.html.erb
<%= render 'form', post: @post, action: 'new' %>

w5d1_capybara_demo/app/views/posts/show.html.erb
<h1></h1>
<nav>
  <div class="nav-wrapper light-blue">
    <div class="col s12">
      <a href="<%= subs_url %>" class="breadcrumb">&nbspAll Subs</a>
      <a href="<%= sub_url(@post.sub) %>" class="breadcrumb"><%= @post.sub.title %></a>
      <a href="#" class="breadcrumb"><%= @post.title %></a>
    </div>
  </div>
</nav>

<h1><%= @post.title  %></h1>
<br>
<p><%= @post.url %></p>
<p><%= @post.content %></p>

<%= link_to 'Edit Post', edit_post_url(@post) %>
<%= link_to 'Back to Sub', sub_url(@post.sub_id) %>

w5d1_capybara_demo/app/views/subs/_form.html.erb
<h1><%= action.capitalize %> A Sub</h1>
<% http = action == 'new' ? 'post' : 'patch' %>
<% url = action == 'new' ? subs_url : sub_url(sub) %>

<div class="row">

  <form class="col s12" action="<%= url %>" method="post">
    <input type="hidden" name="_method" value="<%= http %>">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <input type="hidden" name="sub[mod_id]" value="<%= current_user.id  %>">

    <label for="title">Title: </label>
    <input id='title' type="text" name="sub[title]" value="<%= sub.title %>">
    <br>
    <br>
    <label for="description">Description: </label>
    <textarea id='description' name="sub[description]" rows="8" cols="80"><%= sub.description %></textarea>

    <input type="submit" value="<%= action.capitalize %>Sub">
  </form>
</div>

w5d1_capybara_demo/app/views/subs/edit.html.erb
<%= render 'form', sub: @sub, action: 'edit' %>

w5d1_capybara_demo/app/views/subs/index.html.erb
<h1></h1>
<nav>
  <div class="nav-wrapper light-blue">
    <div class="col s12">
      <a href="<%= subs_url %>" class="breadcrumb">&nbspAll Subs</a>
    </div>
  </div>
</nav>

<ul class="collapsible popout" data-collapsible="accordion">
  <% @subs.each do |sub| %>
    <li>
      <div class="collapsible-header">
        <%= link_to sub.title, sub_url(sub)%>
      </div>
      <div class="collapsible-body">
        <div class="row">
          <div class="col s12">
           <div class="card-panel">
             <span class="black-text">
               <%= sub.description %>
             </span>
           </div>
         </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

<br />

<a class="btn-floating btn-large waves-effect waves-light red" href="<%= new_sub_url %>">
  <i class="material-icons">add</i>
</a>

w5d1_capybara_demo/app/views/subs/new.html.erb
<%= render 'form', sub: @sub, action: 'new' %>

w5d1_capybara_demo/app/views/subs/show.html.erb
<h1></h1>

<nav>
  <div class="nav-wrapper light-blue">
    <div class="col s12">
      <a href="<%= subs_url %>" class="breadcrumb">&nbspAll Subs</a>
      <a href="#" class="breadcrumb"><%= @sub.title %></a>
    </div>
  </div>
</nav>

<h5>
<blockquote><%= @sub.description %></blockquote>
</h5>

<% @sub.posts.each do |post| %>
  <div class="row">
    <div class="col s12">
      <div class="card light-grey darken-1">
        <div class="card-content dark-grey-text">
          <span class="card-title"><%= link_to post.title, post_url(post) %></span>
          <p><%= post.content %></p>
        </div>

      </div>
    </div>
  </div>

<% end %>

<%= link_to 'Add New Post', new_post_url(sub_id: @sub.id) %>

<% unless is_moderator? %>
  <%= link_to 'Edit Sub', edit_sub_url %>
<% end %>

w5d1_capybara_demo/app/views/users/_form.html.erb
<h2>Create An Account</h2>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="username">Username</label>
  <input id='username' type="text" name="user[username]">

  <label for="password">Password</label>
  <input id='password' type="text" name="user[password]">

  <input type="submit" value="Create Account">

</form>

w5d1_capybara_demo/app/views/users/new.html.erb
<%= render 'form' %>